import { EVConfiguration } from '@/types/ev';

export const DEFAULT_CITY_EV: EVConfiguration = {
  id: 'preset-city-ev',
  name: 'City EV',
  description: 'Efficient compact electric hatchback optimized for urban commuting and tight maneuvering.',
  vehicle: {
    massKg: 1250,
    frontalAreaM2: 2.1,
    cd: 0.29,
    crr: 0.011,
    wheelRadiusM: 0.30,
    drivenWheels: 'fwd',
    ambientTempC: 20,
    roadGradePercent: 0,
  },
  motor: {
    type: 'pmsm',
    peakPowerKw: 85,
    continuousPowerKw: 55,
    peakTorqueNm: 220,
    continuousTorqueNm: 140,
    maxRpm: 12000,
    baseEfficiency: 0.94,
  },
  battery: {
    cellNominalVoltage: 3.7,
    cellsInSeries: 96,
    cellsInParallel: 3,
    cellCapacityAh: 40,
    usableSocMinPercent: 5,
    usableSocMaxPercent: 95,
    maxDischargeC: 3.0,
    maxChargeC: 1.2,
    internalResistanceMohm: 35,
    chargingEfficiency: 0.92,
    dischargeEfficiency: 0.96,
    initialSocPercent: 90,
  },
  transmission: {
    gearRatio: 8.2,
    differentialRatio: 1.0,
    drivetrainEfficiency: 0.96,
  },
  regenMode: 'medium',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
};

export const DEFAULT_PERFORMANCE_EV: EVConfiguration = {
  id: 'preset-performance-ev',
  name: 'Performance EV',
  description: 'High-output dual-motor all-wheel-drive sport sedan engineered for rapid acceleration and top track speed.',
  vehicle: {
    massKg: 1850,
    frontalAreaM2: 2.25,
    cd: 0.24,
    crr: 0.012,
    wheelRadiusM: 0.34,
    drivenWheels: 'awd',
    ambientTempC: 20,
    roadGradePercent: 0,
  },
  motor: {
    type: 'pmsm',
    peakPowerKw: 320,
    continuousPowerKw: 190,
    peakTorqueNm: 580,
    continuousTorqueNm: 320,
    maxRpm: 18000,
    baseEfficiency: 0.96,
  },
  battery: {
    cellNominalVoltage: 3.7,
    cellsInSeries: 108,
    cellsInParallel: 4,
    cellCapacityAh: 60,
    usableSocMinPercent: 5,
    usableSocMaxPercent: 95,
    maxDischargeC: 4.5,
    maxChargeC: 2.0,
    internalResistanceMohm: 22,
    chargingEfficiency: 0.94,
    dischargeEfficiency: 0.97,
    initialSocPercent: 90,
  },
  transmission: {
    gearRatio: 9.0,
    differentialRatio: 1.0,
    drivetrainEfficiency: 0.97,
  },
  regenMode: 'high',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
};

export const DEFAULT_DELIVERY_EV: EVConfiguration = {
  id: 'preset-delivery-ev',
  name: 'Delivery Van EV',
  description: 'Heavy-duty electric logistics van designed for high payload, high torque delivery, and stop-and-go duty cycles.',
  vehicle: {
    massKg: 2200,
    frontalAreaM2: 3.4,
    cd: 0.35,
    crr: 0.013,
    wheelRadiusM: 0.36,
    drivenWheels: 'rwd',
    ambientTempC: 20,
    roadGradePercent: 0,
  },
  motor: {
    type: 'induction',
    peakPowerKw: 135,
    continuousPowerKw: 90,
    peakTorqueNm: 380,
    continuousTorqueNm: 250,
    maxRpm: 11000,
    baseEfficiency: 0.92,
  },
  battery: {
    cellNominalVoltage: 3.2, // LFP chemistry
    cellsInSeries: 120,
    cellsInParallel: 3,
    cellCapacityAh: 70,
    usableSocMinPercent: 3,
    usableSocMaxPercent: 98,
    maxDischargeC: 2.5,
    maxChargeC: 1.0,
    internalResistanceMohm: 28,
    chargingEfficiency: 0.91,
    dischargeEfficiency: 0.95,
    initialSocPercent: 95,
  },
  transmission: {
    gearRatio: 10.8,
    differentialRatio: 1.0,
    drivetrainEfficiency: 0.95,
  },
  regenMode: 'high',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
};

export const DEFAULT_CRUISER_EV: EVConfiguration = {
  id: 'preset-cruiser-ev',
  name: 'Long-Range Cruiser',
  description: 'Ultra-aerodynamic grand tourer engineered for maximum highway efficiency and low consumption.',
  vehicle: {
    massKg: 1720,
    frontalAreaM2: 2.15,
    cd: 0.21,
    crr: 0.009,
    wheelRadiusM: 0.32,
    drivenWheels: 'rwd',
    ambientTempC: 20,
    roadGradePercent: 0,
  },
  motor: {
    type: 'pmsm',
    peakPowerKw: 180,
    continuousPowerKw: 110,
    peakTorqueNm: 390,
    continuousTorqueNm: 240,
    maxRpm: 16000,
    baseEfficiency: 0.96,
  },
  battery: {
    cellNominalVoltage: 3.7,
    cellsInSeries: 100,
    cellsInParallel: 4,
    cellCapacityAh: 55,
    usableSocMinPercent: 5,
    usableSocMaxPercent: 95,
    maxDischargeC: 3.5,
    maxChargeC: 1.5,
    internalResistanceMohm: 25,
    chargingEfficiency: 0.93,
    dischargeEfficiency: 0.97,
    initialSocPercent: 90,
  },
  transmission: {
    gearRatio: 8.6,
    differentialRatio: 1.0,
    drivetrainEfficiency: 0.97,
  },
  regenMode: 'medium',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
};

export const PRESET_VEHICLES: EVConfiguration[] = [
  DEFAULT_CITY_EV,
  DEFAULT_PERFORMANCE_EV,
  DEFAULT_DELIVERY_EV,
  DEFAULT_CRUISER_EV,
];
